[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    warn
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Docker_Mode       On
    Refresh_Interval  10

[FILTER]
    Name       parser
    Match      docker.*
    Key_Name   log
    Parser     json
    Reserve_Data On

[OUTPUT]
    Name              http
    Match             *
    Host              ${BETTERSTACK_HOST}
    Port              443
    URI               /
    Format            json
    Header            Authorization Bearer ${BETTERSTACK_TOKEN}
    Header            Content-Type application/json
    tls               On
    tls.verify        On
